import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ToastProvider from "@/providers/ToastProvider";
import 'react-toastify/dist/ReactToastify.css';

import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div id="next">
          <ToastProvider>
            {children}
          </ToastProvider>
          </div>
        </body>
      </html>
    </AuthProvider>
    
  );
}
